### ISSUE TITLE
[bug] AttributeError: 'Namespace' object has no attribute 'auth_username'. Did you mean: 'auth_user'?

### ISSUE THREAD

**Issue by p0dalirius** [p0dalirius/FindUncommonShares#28]
```
FindUncommonShares v3.2 - by @podalirius_

[+] No password of hashes provided and --no-pass is 'False'
Traceback (most recent call last):
  File "/workspace/./f.py", line 891, in <module>
    options = parseArgs()
              ^^^^^^^^^^^
  File "/workspace/./f.py", line 479, in parseArgs
    options.auth_password = getpass("  | Provide a password for '%s\\%s':" % (options.auth_domain, options.auth_username))
                                                                                                   ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'auth_username'. Did you mean: 'auth_user'?
```

**Comment by p0dalirius** [comment]
Fixed in 753e277
